import { NichePack, Niche } from './types';

export const NICHE_PACKS: Record<Niche, NichePack> = {
  HOME_SERVICES: {
    niche: 'HOME_SERVICES',
    packName: 'Reliable Pro',
    keywords: ['plumbing', 'hvac', 'roofing', 'electrician', 'electric', 'contractor', 'handyman', 'repair', 'maintenance', 'install', 'pipe', 'heating', 'cooling', 'roof', 'gutter', 'siding'],
    baseEasing: 'easeOut',
    baseDurations: { fast: 0.2, normal: 0.4, slow: 0.6, reveal: 0.8 },
    staggerRange: { min: 0.05, max: 0.12 },
    heroRevealStyle: 'fadeBlur',
    cardEnterStyle: 'fadeUp',
    cardHoverStyle: 'lift',
    ctaHoverStyle: 'sheen',
    navBehavior: 'fadeSlide',
    flourishPool: ['pressurePulseBadge', 'pipeTraceLine'],
    backgroundAccents: ['lines', 'dots'],
    microEffectPool: ['iconPulse', 'shadowLift', 'buttonSheen', 'scaleOnHover', 'borderGlow', 'arrowBounce', 'checkmarkDraw'],
  },

  AGRICULTURE: {
    niche: 'AGRICULTURE',
    packName: 'Organic Roots',
    keywords: ['farm', 'ranch', 'csa', 'organic', 'agriculture', 'crop', 'harvest', 'livestock', 'dairy', 'produce', 'vegetable', 'fruit', 'grain', 'seed', 'soil'],
    baseEasing: [0.25, 0.46, 0.45, 0.94],
    baseDurations: { fast: 0.3, normal: 0.5, slow: 0.8, reveal: 1.2 },
    staggerRange: { min: 0.08, max: 0.18 },
    heroRevealStyle: 'maskUp',
    cardEnterStyle: 'fadeUp',
    cardHoverStyle: 'glow',
    ctaHoverStyle: 'fill',
    navBehavior: 'stagger',
    flourishPool: ['pollenFloat', 'leafSway', 'sunburstGlow'],
    backgroundAccents: ['grain', 'dots'],
    microEffectPool: ['textShimmer', 'gradientShift', 'imageZoom', 'scaleOnHover', 'glowPulse', 'dotPulse'],
  },

  FITNESS: {
    niche: 'FITNESS',
    packName: 'Power Pulse',
    keywords: ['gym', 'fitness', 'trainer', 'workout', 'exercise', 'crossfit', 'yoga', 'pilates', 'boxing', 'martial', 'sport', 'athletic', 'muscle', 'strength', 'cardio'],
    baseEasing: 'backOut',
    baseDurations: { fast: 0.15, normal: 0.3, slow: 0.5, reveal: 0.6 },
    staggerRange: { min: 0.03, max: 0.08 },
    heroRevealStyle: 'scaleRotate',
    cardEnterStyle: 'bounceIn',
    cardHoverStyle: 'pulse',
    ctaHoverStyle: 'bounce',
    navBehavior: 'scale',
    flourishPool: ['repCounter', 'energySweepUnderline', 'energyRing'],
    backgroundAccents: ['grid', 'lines'],
    microEffectPool: ['iconPulse', 'numberCount', 'progressFill', 'scaleOnHover', 'rotateIcon', 'rippleEffect', 'arrowBounce', 'buttonSheen'],
  },

  RESTAURANT: {
    niche: 'RESTAURANT',
    packName: 'Culinary Elegance',
    keywords: ['restaurant', 'cafe', 'bistro', 'bar', 'food', 'dining', 'cuisine', 'chef', 'kitchen', 'menu', 'catering', 'bakery', 'coffee', 'pizza', 'sushi'],
    baseEasing: 'circOut',
    baseDurations: { fast: 0.25, normal: 0.45, slow: 0.7, reveal: 1.0 },
    staggerRange: { min: 0.06, max: 0.14 },
    heroRevealStyle: 'fadeBlur',
    cardEnterStyle: 'scaleIn',
    cardHoverStyle: 'glow',
    ctaHoverStyle: 'sheen',
    navBehavior: 'blur',
    flourishPool: ['steamWisp', 'menuUnderlineSlider'],
    backgroundAccents: ['grain', 'waves'],
    microEffectPool: ['textShimmer', 'imageZoom', 'gradientShift', 'shadowLift', 'glowPulse', 'scaleOnHover'],
  },

  REAL_ESTATE: {
    niche: 'REAL_ESTATE',
    packName: 'Property Prestige',
    keywords: ['real estate', 'realtor', 'property', 'home', 'house', 'apartment', 'condo', 'listing', 'broker', 'mortgage', 'rental', 'lease', 'commercial', 'residential'],
    baseEasing: [0.16, 1, 0.3, 1],
    baseDurations: { fast: 0.2, normal: 0.4, slow: 0.65, reveal: 0.9 },
    staggerRange: { min: 0.05, max: 0.12 },
    heroRevealStyle: 'slideIn',
    cardEnterStyle: 'slideRight',
    cardHoverStyle: 'tilt',
    ctaHoverStyle: 'glow',
    navBehavior: 'fadeSlide',
    flourishPool: ['listingShimmerLine'],
    backgroundAccents: ['lines', 'grid'],
    microEffectPool: ['imageZoom', 'borderGlow', 'shadowLift', 'underlineSlide', 'scaleOnHover', 'cardTilt', 'textShimmer'],
  },

  HEALTH: {
    niche: 'HEALTH',
    packName: 'Vital Care',
    keywords: ['medical', 'dental', 'doctor', 'clinic', 'hospital', 'health', 'care', 'therapy', 'wellness', 'chiropractic', 'physical', 'mental', 'nurse', 'patient', 'treatment'],
    baseEasing: 'easeInOut',
    baseDurations: { fast: 0.25, normal: 0.45, slow: 0.7, reveal: 0.95 },
    staggerRange: { min: 0.06, max: 0.14 },
    heroRevealStyle: 'fadeBlur',
    cardEnterStyle: 'fadeUp',
    cardHoverStyle: 'glow',
    ctaHoverStyle: 'scale',
    navBehavior: 'stagger',
    flourishPool: ['heartbeatPulse'],
    backgroundAccents: ['orbs', 'dots'],
    microEffectPool: ['iconPulse', 'checkmarkDraw', 'progressFill', 'glowPulse', 'scaleOnHover', 'shadowLift'],
  },

  LEGAL: {
    niche: 'LEGAL',
    packName: 'Justice Authority',
    keywords: ['law', 'lawyer', 'attorney', 'legal', 'court', 'litigation', 'firm', 'counsel', 'advocate', 'paralegal', 'notary', 'contract', 'estate', 'injury', 'defense'],
    baseEasing: [0.4, 0, 0.2, 1],
    baseDurations: { fast: 0.3, normal: 0.5, slow: 0.75, reveal: 1.0 },
    staggerRange: { min: 0.07, max: 0.15 },
    heroRevealStyle: 'maskUp',
    cardEnterStyle: 'fadeUp',
    cardHoverStyle: 'border',
    ctaHoverStyle: 'fill',
    navBehavior: 'fadeSlide',
    flourishPool: ['legalScaleBalance', 'trustBadgeShine'],
    backgroundAccents: ['lines', 'grain'],
    microEffectPool: ['textShimmer', 'underlineSlide', 'shadowLift', 'borderGlow', 'scaleOnHover', 'checkmarkDraw'],
  },

  CREATIVE: {
    niche: 'CREATIVE',
    packName: 'Artisan Flow',
    keywords: ['photography', 'photographer', 'design', 'designer', 'artist', 'creative', 'studio', 'gallery', 'event', 'wedding', 'video', 'film', 'animation', 'illustration', 'graphic'],
    baseEasing: 'anticipate',
    baseDurations: { fast: 0.2, normal: 0.4, slow: 0.7, reveal: 1.1 },
    staggerRange: { min: 0.04, max: 0.1 },
    heroRevealStyle: 'scaleRotate',
    cardEnterStyle: 'flipIn',
    cardHoverStyle: 'tilt',
    ctaHoverStyle: 'glow',
    navBehavior: 'scale',
    flourishPool: ['creativeBrushStroke'],
    backgroundAccents: ['orbs', 'waves'],
    microEffectPool: ['imageZoom', 'gradientShift', 'cardTilt', 'rotateIcon', 'textShimmer', 'glowPulse', 'rippleEffect'],
  },

  SAAS: {
    niche: 'SAAS',
    packName: 'Tech Precision',
    keywords: ['software', 'saas', 'tech', 'technology', 'app', 'platform', 'cloud', 'digital', 'startup', 'ai', 'data', 'analytics', 'automation', 'api', 'developer'],
    baseEasing: [0.22, 1, 0.36, 1],
    baseDurations: { fast: 0.15, normal: 0.3, slow: 0.5, reveal: 0.7 },
    staggerRange: { min: 0.03, max: 0.08 },
    heroRevealStyle: 'typewriter',
    cardEnterStyle: 'scaleIn',
    cardHoverStyle: 'glow',
    ctaHoverStyle: 'sheen',
    navBehavior: 'blur',
    flourishPool: ['gridParallaxGlow', 'circuitGlowTrace'],
    backgroundAccents: ['grid', 'orbs'],
    microEffectPool: ['buttonSheen', 'borderGlow', 'numberCount', 'progressFill', 'iconPulse', 'dotPulse', 'scaleOnHover'],
  },

  RETAIL: {
    niche: 'RETAIL',
    packName: 'Shop Delight',
    keywords: ['shop', 'store', 'retail', 'boutique', 'fashion', 'clothing', 'jewelry', 'gift', 'ecommerce', 'product', 'merchandise', 'sale', 'discount', 'brand'],
    baseEasing: 'easeOut',
    baseDurations: { fast: 0.2, normal: 0.35, slow: 0.55, reveal: 0.75 },
    staggerRange: { min: 0.04, max: 0.1 },
    heroRevealStyle: 'slideIn',
    cardEnterStyle: 'bounceIn',
    cardHoverStyle: 'lift',
    ctaHoverStyle: 'bounce',
    navBehavior: 'stagger',
    flourishPool: ['listingShimmerLine', 'confettiSparkle'],
    backgroundAccents: ['dots', 'waves'],
    microEffectPool: ['imageZoom', 'scaleOnHover', 'buttonSheen', 'shadowLift', 'glowPulse', 'arrowBounce'],
  },

  EDUCATION: {
    niche: 'EDUCATION',
    packName: 'Learn & Grow',
    keywords: ['school', 'education', 'tutor', 'training', 'course', 'class', 'academy', 'university', 'college', 'learning', 'teach', 'student', 'degree', 'certification'],
    baseEasing: 'easeInOut',
    baseDurations: { fast: 0.25, normal: 0.45, slow: 0.7, reveal: 0.9 },
    staggerRange: { min: 0.06, max: 0.13 },
    heroRevealStyle: 'fadeBlur',
    cardEnterStyle: 'fadeUp',
    cardHoverStyle: 'lift',
    ctaHoverStyle: 'scale',
    navBehavior: 'fadeSlide',
    flourishPool: ['pollenFloat'],
    backgroundAccents: ['dots', 'grain'],
    microEffectPool: ['progressFill', 'checkmarkDraw', 'numberCount', 'iconPulse', 'scaleOnHover', 'textShimmer'],
  },

  AUTOMOTIVE: {
    niche: 'AUTOMOTIVE',
    packName: 'Drive Force',
    keywords: ['auto', 'car', 'vehicle', 'mechanic', 'repair', 'tire', 'oil', 'engine', 'transmission', 'brake', 'dealership', 'detailing', 'body', 'collision'],
    baseEasing: 'backOut',
    baseDurations: { fast: 0.18, normal: 0.35, slow: 0.55, reveal: 0.7 },
    staggerRange: { min: 0.04, max: 0.1 },
    heroRevealStyle: 'slideIn',
    cardEnterStyle: 'slideRight',
    cardHoverStyle: 'pulse',
    ctaHoverStyle: 'sheen',
    navBehavior: 'scale',
    flourishPool: ['pressurePulseBadge'],
    backgroundAccents: ['lines', 'grid'],
    microEffectPool: ['iconPulse', 'rotateIcon', 'progressFill', 'numberCount', 'buttonSheen', 'scaleOnHover'],
  },

  BEAUTY: {
    niche: 'BEAUTY',
    packName: 'Radiant Glow',
    keywords: ['salon', 'spa', 'beauty', 'hair', 'nail', 'makeup', 'skincare', 'cosmetic', 'aesthetic', 'lash', 'brow', 'facial', 'massage', 'treatment', 'stylist'],
    baseEasing: 'circOut',
    baseDurations: { fast: 0.25, normal: 0.45, slow: 0.7, reveal: 1.0 },
    staggerRange: { min: 0.06, max: 0.14 },
    heroRevealStyle: 'fadeBlur',
    cardEnterStyle: 'scaleIn',
    cardHoverStyle: 'glow',
    ctaHoverStyle: 'glow',
    navBehavior: 'blur',
    flourishPool: ['steamWisp'],
    backgroundAccents: ['orbs', 'waves'],
    microEffectPool: ['glowPulse', 'textShimmer', 'gradientShift', 'imageZoom', 'shadowLift', 'scaleOnHover'],
  },

  GENERIC: {
    niche: 'GENERIC',
    packName: 'Modern Standard',
    keywords: [],
    baseEasing: 'easeOut',
    baseDurations: { fast: 0.2, normal: 0.4, slow: 0.6, reveal: 0.8 },
    staggerRange: { min: 0.05, max: 0.12 },
    heroRevealStyle: 'fadeBlur',
    cardEnterStyle: 'fadeUp',
    cardHoverStyle: 'lift',
    ctaHoverStyle: 'sheen',
    navBehavior: 'fadeSlide',
    flourishPool: ['none'],
    backgroundAccents: ['dots', 'none'],
    microEffectPool: ['scaleOnHover', 'shadowLift', 'buttonSheen', 'iconPulse', 'imageZoom'],
  },
};

export const ALL_NICHES: Niche[] = Object.keys(NICHE_PACKS) as Niche[];
